my:
  greeting: Updated hello world from spring-boot-config microsevice specific file
  list:
    values: One,Two,Three

db:
  connection: connection-string-here-from-config-server
  host: 127.0.0.1
  port: 1200